// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// What an adapter can do: the optional features and the limits, each mapped
// onto the four APIs in docs/contract/mappings.md.
//
// Generated by tools/gen_contract.py from docs/contract/mrhi.json: edit the
// contract, not this file.

#ifndef MAUL_RHI_CAPABILITIES_H
#define MAUL_RHI_CAPABILITIES_H

#include "maul-rhi/instance.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

    // The optional features (mrhi-0006). The floor (compute, indirect draws,
    // instancing, the texture kinds, independent blend, occlusion queries)
    // needs no request.
    typedef struct mrhiFeatures
    {
        // Timestamps at pass boundaries (mrhi-0006).
        bool timestampQuery;
        // Pipeline statistics queries.
        bool pipelineStatisticsQuery;
        // BC1 to BC7 textures.
        bool textureCompressionBc;
        // ETC2 and EAC textures.
        bool textureCompressionEtc2;
        // ASTC LDR textures.
        bool textureCompressionAstc;
        // Filtering of 32-bit float textures.
        bool float32Filterable;
        // Rendering to rg11b10ufloat.
        bool rg11b10Renderable;
        // Blending with a second fragment output.
        bool dualSourceBlending;
        // Depth clamped instead of clipped, for shadow pancaking.
        bool unclippedDepth;
        // 16-bit floats in shaders.
        bool shaderF16;
        // Subgroup operations.
        bool subgroups;
        // 64-bit integers in shaders.
        bool shaderInt64;
        // A first instance other than zero in indirect draws.
        bool indirectFirstInstance;
        // Multi-draw indirect with a GPU-written count.
        bool multiDrawIndirectCount;
        // Rendering several views in one pass.
        bool multiview;
        // A heap of sampled textures and samplers.
        bool bindlessSampling;
        // A heap of every resource kind but uniform buffers.
        bool bindlessHeterogeneous;
        // Presentation timestamps and a target present time.
        bool presentTiming;
    } mrhiFeatures;

    // The limits (mrhi-0006): WebGPU's floor in the contract's terms. An
    // adapter reports its values; a device def requests values, the defaults
    // being the floor.
    typedef struct mrhiLimits
    {
        // The width and height of a 2D or cube texture.
        uint32_t textureDimension2d;
        // Each dimension of a 3D texture.
        uint32_t textureDimension3d;
        // The layers of an array texture.
        uint32_t textureArrayLayers;
        // Binding tables a pipeline declares.
        uint32_t bindingTables;
        // Slots in one binding table.
        uint32_t bindingsPerTable;
        // Sampled textures one shader stage binds.
        uint32_t sampledTexturesPerStage;
        // Samplers one shader stage binds.
        uint32_t samplersPerStage;
        // Storage buffers one shader stage binds.
        uint32_t storageBuffersPerStage;
        // Storage textures one shader stage binds.
        uint32_t storageTexturesPerStage;
        // Uniform buffers one shader stage binds.
        uint32_t uniformBuffersPerStage;
        // The bytes of one uniform buffer binding.
        uint32_t uniformBindingBytes;
        // The bytes of one storage buffer binding.
        uint64_t storageBindingBytes;
        // The alignment of a uniform binding's offset; lower is better.
        uint32_t uniformOffsetAlignment;
        // The alignment of a storage binding's offset; lower is better.
        uint32_t storageOffsetAlignment;
        // Vertex buffers a pipeline reads.
        uint32_t vertexBuffers;
        // Binding tables and vertex buffers together.
        uint32_t tablesPlusVertexBuffers;
        // The bytes of one buffer.
        uint64_t bufferBytes;
        // Vertex attributes a pipeline reads.
        uint32_t vertexAttributes;
        // The stride of one vertex buffer.
        uint32_t vertexStride;
        // Four-component variables passed between shader stages.
        uint32_t interStageVariables;
        // Color targets of one render pass.
        uint32_t colorAttachments;
        // The bytes of all color targets in one sample.
        uint32_t colorBytesPerSample;
        // The workgroup memory of one compute pipeline.
        uint32_t workgroupStorageBytes;
        // The invocations of one workgroup.
        uint32_t workgroupInvocations;
        // A workgroup's size in x.
        uint32_t workgroupSizeX;
        // A workgroup's size in y.
        uint32_t workgroupSizeY;
        // A workgroup's size in z.
        uint32_t workgroupSizeZ;
        // Workgroups one dispatch has in each dimension.
        uint32_t workgroupsPerDimension;
        // The bytes of the root block each draw or dispatch sets.
        uint32_t rootBlockBytes;
        // Entries of the resource heap; 0 without a bindless feature, at most
        // 65536 portably.
        uint32_t heapSize;
        // Entries of the sampler heap; 0 without a bindless feature.
        uint32_t samplerHeapSize;
        // Frames recorded while earlier ones still run on the GPU.
        uint32_t framesInFlight;
    } mrhiLimits;

    /// Returns the floor limits, which every adapter of every driver meets:
    /// WebGPU's defaults, 64 root block bytes, no heaps and 2 frames in flight.
    ///
    /// @return The floor.
    /// @par Thread safety
    /// Safe from any thread.
    MRHI_API mrhiLimits mrhiDefaultLimits(void);

    /// Reads the optional features an adapter can grant.
    ///
    /// @param instance     The instance.
    /// @param adapter      The adapter.
    /// @param featuresOut  Receives the features.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument;
    /// `mrhi_errorStale` for an adapter the instance no longer has.
    /// @par Thread safety
    /// Safe from any thread; the instance is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiGetAdapterFeatures(mrhiInstance* instance,
                                                              mrhiAdapterId adapter,
                                                              mrhiFeatures* featuresOut);

    /// Reads the limits an adapter can grant, each at least the floor.
    ///
    /// @param instance   The instance.
    /// @param adapter    The adapter.
    /// @param limitsOut  Receives the limits.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument;
    /// `mrhi_errorStale` for an adapter the instance no longer has.
    /// @par Thread safety
    /// Safe from any thread; the instance is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiGetAdapterLimits(mrhiInstance* instance,
                                                            mrhiAdapterId adapter,
                                                            mrhiLimits* limitsOut);

#ifdef __cplusplus
}
#endif

#endif // MAUL_RHI_CAPABILITIES_H
