// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// The device: the second root of Maul RHI, opened on an adapter with the
// features and limits a program asks for, and the owner of every GPU object.
//
// Generated by tools/gen_contract.py from docs/contract/mrhi.json: edit the
// contract, not this file.

#ifndef MAUL_RHI_DEVICE_H
#define MAUL_RHI_DEVICE_H

#include "maul-rhi/capabilities.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

    // A device, made by mrhiCreateDevice.
    typedef struct mrhiDevice mrhiDevice;

    // Where a device is in its life.
    typedef uint8_t mrhiDeviceState;

    enum
    {
        // Made, not yet ready: calls answer mrhi_errorState.
        mrhi_deviceOpening = 0,
        // Ready for use.
        mrhi_deviceReady = 1,
        // Opening failed; only destroying it remains.
        mrhi_deviceFailed = 2,
        // The GPU or its driver was lost; only destroying it remains.
        mrhi_deviceLost = 3,
    };

    // The named limits of a device's own bookkeeping.
    typedef struct mrhiDeviceLimits
    {
        // Records the device's notification queue holds; 256 by default.
        uint32_t notifications;
        // Samplers the device holds at once; 256 by default.
        uint32_t samplers;
        // Buffers the device holds at once; 4096 by default.
        uint32_t buffers;
        // Textures the device holds at once; 4096 by default.
        uint32_t textures;
        // Views the device holds at once; 8192 by default.
        uint32_t views;
        // Surfaces the device configures at once; 8 by default.
        uint32_t surfaces;
        // Resources one frame declares and imports; 1024 by default.
        uint32_t frameResources;
        // Passes one frame declares; 256 by default.
        uint32_t framePasses;
        // Accesses and targets one frame's passes declare in all; 4096 by
        // default.
        uint32_t frameAccesses;
        // Barriers one frame's compile plans; 4096 by default.
        uint32_t frameBarriers;
        // Shader containers the device holds at once; 256 by default.
        uint32_t shaders;
        // Graphics and compute pipelines the device holds at once; 1024 by
        // default.
        uint32_t pipelines;
        // The bytes one frame's commands take in all, in 4 KiB chunks; 1 MiB by
        // default.
        uint32_t frameCommandBytes;
    } mrhiDeviceLimits;

    // How a device is made. Build it with mrhiDefaultDeviceDef and set the
    // adapter.
    typedef struct mrhiDeviceDef
    {
        uint32_t cookie;
        // Extensions, or NULL.
        const mrhiChain* next;
        // A name for debugging tools: UTF-8 without NUL, labelLength bytes, at
        // most MRHI_LABEL_BYTES; NULL when labelLength is 0. Only read during
        // the call.
        const char* label;
        // The label's bytes.
        size_t labelLength;
        // The adapter to open, from mrhiGetAdapters.
        mrhiAdapterId adapter;
        // The optional features asked for.
        mrhiFeatures features;
        // The limits asked for, at least the floor.
        mrhiLimits limits;
        mrhiDeviceLimits deviceLimits;
        mrhiAllocator allocator;
        // A pipeline cache mrhiGetPipelineCache wrote, or NULL: checked as
        // hostile input, it is used when it came from this library version,
        // driver and adapter, and otherwise ignored. Only read during the call.
        const void* pipelineCache;
        // Its size.
        size_t pipelineCacheBytes;
    } mrhiDeviceDef;

    /// Returns the default device def: no adapter, no optional features, the
    /// floor limits, 256 notifications, 256 samplers, 4096 buffers, 4096
    /// textures and the C library's allocator.
    ///
    /// @return The def, with a valid cookie.
    /// @par Thread safety
    /// Safe from any thread.
    MRHI_API mrhiDeviceDef mrhiDefaultDeviceDef(void);

    /// Makes a device on an adapter. It returns at once with the device
    /// opening, and the instance's queue answers the request with
    /// mrhi_instanceDeviceReady.
    ///
    /// @param instance    The instance that found the adapter.
    /// @param def         The device to make.
    /// @param deviceOut   Receives the device; set to NULL on failure.
    /// @param requestOut  Receives the id its ready record answers.
    /// @return `mrhi_success` with the device opening; `mrhi_errorInvalid` for
    /// a NULL argument, a def without its cookie, a label that is not UTF-8
    /// without NUL within MRHI_LABEL_BYTES, a zero limit, limits below the
    /// floor or an allocator with one function; `mrhi_errorStale` for an
    /// adapter the instance no longer has; `mrhi_errorUnsupported` for features
    /// or limits beyond the adapter's, or a critical extension the library does
    /// not know; `mrhi_errorCapacity` when the instance's queue has no room for
    /// the answer or an allocator fails.
    /// @par Thread safety
    /// Safe from any thread; the instance is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiCreateDevice(mrhiInstance* instance,
                                                        const mrhiDeviceDef* def,
                                                        mrhiDevice** deviceOut,
                                                        mrhiRequestId* requestOut);

    /// Destroys a device in any state, and ends the configurations of the
    /// surfaces it configured. A device still opening answers its request with
    /// mrhi_errorStale.
    ///
    /// @param device  The device, or NULL for nothing.
    /// @par Thread safety
    /// Safe from any thread; the device and its instance are used by one thread
    /// at a time.
    MRHI_API void mrhiDestroyDevice(mrhiDevice* device);

    /// Returns where a device is in its life. Draining the instance's queue is
    /// what moves an opening device on.
    ///
    /// @param device  The device.
    /// @return The state; mrhi_deviceFailed for a NULL device.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_API mrhiDeviceState mrhiGetDeviceState(mrhiDevice* device);

    /// Reads the optional features a device was granted.
    ///
    /// @param device       The device.
    /// @param featuresOut  Receives the features.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiGetDeviceFeatures(mrhiDevice* device,
                                                             mrhiFeatures* featuresOut);

    /// Reads the limits a device was granted.
    ///
    /// @param device     The device.
    /// @param limitsOut  Receives the limits.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiGetDeviceLimits(mrhiDevice* device,
                                                           mrhiLimits* limitsOut);

    /// Returns how many calls the device has refused as invalid input
    /// (mrhi_errorInvalid).
    ///
    /// @param device  The device.
    /// @return The count; 0 for a NULL device.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_API uint64_t mrhiGetDeviceMisuse(mrhiDevice* device);

#ifdef __cplusplus
}
#endif

#endif // MAUL_RHI_DEVICE_H
