// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// Recording: a kept pass of a compiled frame is begun, its commands recorded,
// and ended, all before the frame is submitted. The pass id is the encoder.
// Different passes may record on different threads at once; while passes
// record, nothing else uses the device.
//
// Generated by tools/gen_contract.py from docs/contract/mrhi.json: edit the
// contract, not this file.

#ifndef MAUL_RHI_ENCODER_H
#define MAUL_RHI_ENCODER_H

#include "maul-rhi/pipeline.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

    // Where rendering lands: a rectangle of the targets and a depth range.
    typedef struct mrhiViewport
    {
        // Its left edge, at least -2 times the 2D texture limit.
        float x;
        // Its top edge, likewise.
        float y;
        // Its width, 0 to the 2D texture limit; the right edge at most 2 times
        // the limit minus 1.
        float width;
        // Its height, likewise.
        float height;
        // The depth its near plane maps to, 0 to 1.
        float minDepth;
        // The depth its far plane maps to, minDepth to 1.
        float maxDepth;
    } mrhiViewport;

    // The pixels rendering may write, within the pass's targets.
    typedef struct mrhiScissorRect
    {
        // Its left edge.
        uint32_t x;
        // Its top edge.
        uint32_t y;
        // Its width.
        uint32_t width;
        // Its height.
        uint32_t height;
    } mrhiScissorRect;

// A buffer binding's size that reaches the buffer's end.
#define MRHI_WHOLE_SIZE 0xFFFFFFFFFFFFFFFFu

    // One slot of a binding table: a buffer range, a texture view or a sampler,
    // as the slot's kind in the shader needs.
    typedef struct mrhiBinding
    {
        // The slot, one of the table's in the pipeline's shader.
        uint32_t slot;
        // A buffer or texture of the open frame; a null id for a sampler.
        mrhiResourceId resource;
        // A buffer's first byte, aligned to the device's uniformOffsetAlignment
        // or storageOffsetAlignment.
        uint64_t offset;
        // A buffer's bytes from the offset, or MRHI_WHOLE_SIZE for the rest;
        // within the device's uniformBindingBytes or storageBindingBytes, at
        // least the shader's minimum, and a multiple of 4 for storage.
        uint64_t size;
        // A texture's shape as the shader sees it, as a view's kind: 2D or 2D
        // array on any texture but a 3D one, a cube or cube array on a cube or
        // cube array texture, 3D on a 3D texture.
        mrhiTextureKind viewKind;
        // The texture's format or one of its view formats; mrhi_formatNone for
        // the texture's.
        mrhiFormat viewFormat;
        // A texture's mips, layers and aspect; one mip for a storage texture.
        mrhiTextureRange range;
        // A sampler, for a sampler slot.
        mrhiSamplerId sampler;
    } mrhiBinding;

    /// Begins recording a kept pass of the compiled open frame. It records
    /// until mrhiEndPass; a kept pass never begun records nothing.
    ///
    /// @param device  The device.
    /// @param pass    The pass.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL device;
    /// `mrhi_errorStale` for a pass of another frame or none; `mrhi_errorState`
    /// for a pass that is culled, begun already, or a frame that is not
    /// compiled.
    /// @par Thread safety
    /// Safe from any thread; the pass is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiBeginPass(mrhiDevice* device, mrhiPassId pass);

    /// Ends recording a pass. Its debug groups must be closed.
    ///
    /// @param device  The device.
    /// @param pass    The pass, recording.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL device or open
    /// debug groups; `mrhi_errorStale` for a pass of another frame or none;
    /// `mrhi_errorState` for a pass that is not recording.
    /// @par Thread safety
    /// Safe from any thread; the pass is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiEndPass(mrhiDevice* device, mrhiPassId pass);

    /// Sets the graphics pipeline later draws use, in a pass with targets. It
    /// must be ready and fit the pass's targets: their formats and sample
    /// count, and no depth or stencil writes to a read-only depth target.
    ///
    /// @param device    The device.
    /// @param pass      The pass, recording.
    /// @param pipeline  The pipeline.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL device, a pass
    /// without targets, or a pipeline that does not fit its targets;
    /// `mrhi_errorStale` for a pass of another frame or none; `mrhi_errorState`
    /// for a pass that is not recording, or a pipeline that is not ready;
    /// `mrhi_errorStale` also for a pipeline the device no longer has;
    /// `mrhi_errorCapacity` when the frame's commands are full.
    /// @par Thread safety
    /// Safe from any thread; the pass is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiSetGraphicsPipeline(mrhiDevice* device, mrhiPassId pass,
                                                               mrhiGraphicsPipelineId pipeline);

    /// Sets the compute pipeline later dispatches use, in a pass without
    /// targets.
    ///
    /// @param device    The device.
    /// @param pass      The pass, recording.
    /// @param pipeline  The pipeline.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL device or a pass
    /// that renders or copies; `mrhi_errorStale` for a pass of another frame or
    /// none; `mrhi_errorState` for a pass that is not recording, or a pipeline
    /// that is not ready; `mrhi_errorStale` also for a pipeline the device no
    /// longer has; `mrhi_errorCapacity` when the frame's commands are full.
    /// @par Thread safety
    /// Safe from any thread; the pass is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiSetComputePipeline(mrhiDevice* device, mrhiPassId pass,
                                                              mrhiComputePipelineId pipeline);

    /// Sets every slot of one binding table for later draws or dispatches,
    /// checked against the pass's pipeline and its declared accesses.
    ///
    /// @param device    The device.
    /// @param pass      The pass, recording, with a pipeline set.
    /// @param table     The table, one the pipeline's shader declares.
    /// @param bindings  The bindings, one per slot of the table in any order;
    ///                  NULL when count is 0. Only read during the call.
    /// @param count     How many.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL device or
    /// bindings with a count, a pass that copies, a table past the device's
    /// bindingTables, bindings that are not exactly the table's slots in the
    /// shader, a binding its slot's kind does not take (a range out of bounds
    /// or unaligned, a view invalid for its texture or of another kind, format
    /// or sample type, a sampler of another kind), or a resource the pass
    /// declares no covering access of the needed kind for; `mrhi_errorStale`
    /// for a pass of another frame, a destroyed pipeline, or a resource or
    /// sampler that is not live; `mrhi_errorState` for a pass that is not
    /// recording or has no pipeline set; `mrhi_errorCapacity` when the frame's
    /// commands are full.
    /// @par Thread safety
    /// Safe from any thread; the pass is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiSetBindings(mrhiDevice* device, mrhiPassId pass,
                                                       uint32_t table, const mrhiBinding* bindings,
                                                       uint32_t count);

    /// Writes bytes of the root block later draws or dispatches read.
    ///
    /// @param device  The device.
    /// @param pass    The pass, recording.
    /// @param offset  Where the bytes go in the root block, a multiple of 4.
    /// @param bytes   The bytes. Only read during the call.
    /// @param size    How many, a multiple of 4 and at least 4, ending within
    ///                the device's root block.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL device or bytes,
    /// a pass that copies, or an unaligned or empty write;
    /// `mrhi_errorUnsupported` for a write past the device's root block;
    /// `mrhi_errorStale` for a pass of another frame or none; `mrhi_errorState`
    /// for a pass that is not recording; `mrhi_errorCapacity` when the frame's
    /// commands are full.
    /// @par Thread safety
    /// Safe from any thread; the pass is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiSetRootBlock(mrhiDevice* device, mrhiPassId pass,
                                                        uint32_t offset, const void* bytes,
                                                        uint32_t size);

    /// Sets where later draws land, in a pass with targets.
    ///
    /// @param device    The device.
    /// @param pass      The pass, recording.
    /// @param viewport  The viewport, finite, within WebGPU's ranges.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument, a pass
    /// without targets, or a viewport out of range; `mrhi_errorStale` for a
    /// pass of another frame or none; `mrhi_errorState` for a pass that is not
    /// recording; `mrhi_errorCapacity` when the frame's commands are full.
    /// @par Thread safety
    /// Safe from any thread; the pass is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiSetViewport(mrhiDevice* device, mrhiPassId pass,
                                                       const mrhiViewport* viewport);

    /// Sets the pixels later draws may write, in a pass with targets.
    ///
    /// @param device  The device.
    /// @param pass    The pass, recording.
    /// @param rect    The rectangle, within the targets.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument, a pass
    /// without targets, or a rectangle past them; `mrhi_errorStale` for a pass
    /// of another frame or none; `mrhi_errorState` for a pass that is not
    /// recording; `mrhi_errorCapacity` when the frame's commands are full.
    /// @par Thread safety
    /// Safe from any thread; the pass is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiSetScissor(mrhiDevice* device, mrhiPassId pass,
                                                      const mrhiScissorRect* rect);

    /// Sets the constant blend factors use, in a pass with targets.
    ///
    /// @param device  The device.
    /// @param pass    The pass, recording.
    /// @param color   The constant, finite.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument, a pass
    /// without targets, or a component that is not finite; `mrhi_errorStale`
    /// for a pass of another frame or none; `mrhi_errorState` for a pass that
    /// is not recording; `mrhi_errorCapacity` when the frame's commands are
    /// full.
    /// @par Thread safety
    /// Safe from any thread; the pass is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiSetBlendConstant(mrhiDevice* device, mrhiPassId pass,
                                                            const mrhiClearColor* color);

    /// Sets the reference stencil tests compare with, in a pass with targets.
    ///
    /// @param device     The device.
    /// @param pass       The pass, recording.
    /// @param reference  The reference.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL device or a pass
    /// without targets; `mrhi_errorStale` for a pass of another frame or none;
    /// `mrhi_errorState` for a pass that is not recording; `mrhi_errorCapacity`
    /// when the frame's commands are full.
    /// @par Thread safety
    /// Safe from any thread; the pass is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiSetStencilReference(mrhiDevice* device, mrhiPassId pass,
                                                               uint32_t reference);

    /// Opens a named group of the pass's commands for debugging tools.
    ///
    /// @param device       The device.
    /// @param pass         The pass, recording.
    /// @param label        Its name: UTF-8 without NUL, labelLength bytes, 1 to
    ///                     MRHI_LABEL_BYTES. Only read during the call.
    /// @param labelLength  The name's bytes.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL device or a bad
    /// label; `mrhi_errorStale` for a pass of another frame or none;
    /// `mrhi_errorState` for a pass that is not recording; `mrhi_errorCapacity`
    /// when the frame's commands are full.
    /// @par Thread safety
    /// Safe from any thread; the pass is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiPushDebugGroup(mrhiDevice* device, mrhiPassId pass,
                                                          const char* label, size_t labelLength);

    /// Closes the pass's innermost open debug group.
    ///
    /// @param device  The device.
    /// @param pass    The pass, recording.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL device or no open
    /// group; `mrhi_errorStale` for a pass of another frame or none;
    /// `mrhi_errorState` for a pass that is not recording; `mrhi_errorCapacity`
    /// when the frame's commands are full.
    /// @par Thread safety
    /// Safe from any thread; the pass is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiPopDebugGroup(mrhiDevice* device, mrhiPassId pass);

    /// Marks a point among the pass's commands for debugging tools.
    ///
    /// @param device       The device.
    /// @param pass         The pass, recording.
    /// @param label        Its name: UTF-8 without NUL, labelLength bytes, 1 to
    ///                     MRHI_LABEL_BYTES. Only read during the call.
    /// @param labelLength  The name's bytes.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL device or a bad
    /// label; `mrhi_errorStale` for a pass of another frame or none;
    /// `mrhi_errorState` for a pass that is not recording; `mrhi_errorCapacity`
    /// when the frame's commands are full.
    /// @par Thread safety
    /// Safe from any thread; the pass is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiInsertDebugMarker(mrhiDevice* device, mrhiPassId pass,
                                                             const char* label, size_t labelLength);

#ifdef __cplusplus
}
#endif

#endif // MAUL_RHI_ENCODER_H
