// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// Frames: the frame graph, the only way work reaches the GPU. A frame is begun,
// its resources and passes declared, compiled, recorded and submitted;
// submitting returns a token that the device's notification queue answers once
// the GPU has finished.
//
// Generated by tools/gen_contract.py from docs/contract/mrhi.json: edit the
// contract, not this file.

#ifndef MAUL_RHI_FRAME_H
#define MAUL_RHI_FRAME_H

#include "maul-rhi/surface.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

    // How a frame begins: its extensions. Build it with mrhiDefaultFrameDef.
    typedef struct mrhiFrameDef
    {
        uint32_t cookie;
        // Extensions, or NULL.
        const mrhiChain* next;
    } mrhiFrameDef;

    // What a device notification reports.
    typedef uint8_t mrhiDeviceNotificationKind;

    enum
    {
        // A submitted frame finished on the GPU: its outcome is mrhi_success,
        // or the error that ended it.
        mrhi_deviceFrameDone = 0,
    };

    // A record from a device's notification queue.
    typedef struct mrhiDeviceNotification
    {
        mrhiDeviceNotificationKind kind;
        // The request the record answers: a frame's token.
        mrhiRequestId requestId;
        // How the request ended.
        mrhiResult outcome;
    } mrhiDeviceNotification;

    /// Returns the default frame def.
    ///
    /// @return The def, with a valid cookie.
    /// @par Thread safety
    /// Safe from any thread.
    MRHI_API mrhiFrameDef mrhiDefaultFrameDef(void);

    /// Opens a frame on a ready device, first taking in the frames the GPU
    /// finished. One frame is open at a time.
    ///
    /// @param device  The device.
    /// @param def     The frame.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument or a def
    /// without its cookie; `mrhi_errorUnsupported` for a critical extension the
    /// library does not know; `mrhi_errorState` for a device that is not ready
    /// or has a frame open; `mrhi_errorCapacity` while the device's
    /// framesInFlight frames are still running, until one finishes.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiBeginFrame(mrhiDevice* device, const mrhiFrameDef* def);

    /// Closes the open frame without running it. It gets no token.
    ///
    /// @param device  The device.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL device;
    /// `mrhi_errorState` for a device without an open frame.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiDropFrame(mrhiDevice* device);

    /// Submits the open frame to the GPU and closes it. Its token is answered
    /// by one mrhi_deviceFrameDone record.
    ///
    /// @param device    The device.
    /// @param tokenOut  Receives the frame's token.
    /// @return `mrhi_success` with the token; `mrhi_errorInvalid` for a NULL
    /// argument; `mrhi_errorState` for a device without an open frame;
    /// `mrhi_errorCapacity` when the device's queue has no room for the answer,
    /// the frame staying open; `mrhi_errorPlatform` when the driver fails, the
    /// frame closing.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiSubmitFrame(mrhiDevice* device, mrhiRequestId* tokenOut);

    /// Waits until a submitted frame finishes on the GPU, or the deadline
    /// passes. On the web, where nothing may block, a frame not yet finished
    /// times out at once.
    ///
    /// @param device     The device.
    /// @param token      The frame's token.
    /// @param timeoutNs  The longest wait in nanoseconds; 0 only checks.
    /// @return `mrhi_success` once the frame has finished; `mrhi_timeout` when
    /// the deadline passed first; `mrhi_errorInvalid` for a NULL device or a
    /// token the device never gave.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiWaitFrame(mrhiDevice* device, mrhiRequestId token,
                                                     uint64_t timeoutNs);

    /// Takes the oldest record from the device's notification queue, first
    /// taking in the frames the GPU finished.
    ///
    /// @param device           The device.
    /// @param notificationOut  Receives the record.
    /// @return `mrhi_success` with a record; `mrhi_empty` when the queue is
    /// drained; `mrhi_errorInvalid` for a NULL argument.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult
    mrhiNextDeviceNotification(mrhiDevice* device, mrhiDeviceNotification* notificationOut);

    // A resource of the open frame: a declared texture or buffer, or an
    // imported one. It ends with the frame.
    typedef struct mrhiResourceId
    {
        uint32_t index1;
        uint32_t generation;
    } mrhiResourceId;

    /// Declares a texture the open frame's graph makes, aliases and ends with
    /// the frame. Its usages are derived from the passes that use it, and
    /// checked against its format when the frame is compiled.
    ///
    /// @param device       The device.
    /// @param def          The texture, with a usage of 0.
    /// @param resourceOut  Receives the frame's id for it.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument, a def
    /// without its cookie, a label that is not UTF-8 without NUL within
    /// MRHI_LABEL_BYTES, a usage other than 0, or a shape mrhiCreateTexture
    /// refuses as invalid; `mrhi_errorUnsupported` for a size past the device's
    /// limits, a compressed format without its feature, or a critical extension
    /// the library does not know; `mrhi_errorState` for a device without an
    /// open frame; `mrhi_errorCapacity` when the device's frameResources limit
    /// is reached.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiDeclareTexture(mrhiDevice* device,
                                                          const mrhiTextureDef* def,
                                                          mrhiResourceId* resourceOut);

    /// Declares a buffer the open frame's graph makes, aliases and ends with
    /// the frame. Its usages are derived from the passes that use it.
    ///
    /// @param device       The device.
    /// @param def          The buffer, with a usage of 0.
    /// @param resourceOut  Receives the frame's id for it.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument, a def
    /// without its cookie, a label that is not UTF-8 without NUL within
    /// MRHI_LABEL_BYTES, a usage other than 0, or a size that is zero or not a
    /// multiple of 4; `mrhi_errorUnsupported` for a size past the device's
    /// bufferBytes, or a critical extension the library does not know;
    /// `mrhi_errorState` for a device without an open frame;
    /// `mrhi_errorCapacity` when the device's frameResources limit is reached.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiDeclareBuffer(mrhiDevice* device,
                                                         const mrhiBufferDef* def,
                                                         mrhiResourceId* resourceOut);

    /// Brings a device texture into the open frame, whose graph tracks it and
    /// never aliases it. Importing it again returns the same id.
    ///
    /// @param device       The device.
    /// @param texture      The texture.
    /// @param resourceOut  Receives the frame's id for it.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument;
    /// `mrhi_errorStale` for a texture the device no longer has;
    /// `mrhi_errorState` for a device without an open frame;
    /// `mrhi_errorCapacity` when the device's frameResources limit is reached.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiImportTexture(mrhiDevice* device, mrhiTextureId texture,
                                                         mrhiResourceId* resourceOut);

    /// Brings a device buffer into the open frame, whose graph tracks it and
    /// never aliases it. Importing it again returns the same id.
    ///
    /// @param device       The device.
    /// @param buffer       The buffer.
    /// @param resourceOut  Receives the frame's id for it.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument;
    /// `mrhi_errorStale` for a buffer the device no longer has;
    /// `mrhi_errorState` for a device without an open frame;
    /// `mrhi_errorCapacity` when the device's frameResources limit is reached.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiImportBuffer(mrhiDevice* device, mrhiBufferId buffer,
                                                        mrhiResourceId* resourceOut);

#ifdef __cplusplus
}
#endif

#endif // MAUL_RHI_FRAME_H
