// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// The instance: the root of Maul RHI, made first and destroyed last, which
// negotiates the contract version and finds the adapters.
//
// Generated by tools/gen_contract.py from docs/contract/mrhi.json: edit the
// contract, not this file.

#ifndef MAUL_RHI_INSTANCE_H
#define MAUL_RHI_INSTANCE_H

#include "maul-rhi/base.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

    // An instance, made by mrhiCreateInstance.
    typedef struct mrhiInstance mrhiInstance;

    // The named limits of an instance.
    typedef struct mrhiInstanceLimits
    {
        // Chained structs one def may carry; 8 by default.
        uint32_t chainDepth;
    } mrhiInstanceLimits;

    // How an instance is made. Build it with mrhiDefaultInstanceDef.
    typedef struct mrhiInstanceDef
    {
        uint32_t cookie;
        // Extensions, or NULL.
        const mrhiChain* next;
        // MRHI_CONTRACT_VERSION, as the program was built.
        uint32_t contractVersion;
        mrhiAllocator allocator;
        mrhiInstanceLimits limits;
    } mrhiInstanceDef;

    /// Returns the default instance def: the contract version the program is
    /// built against, the C library's allocator and the default limits (8
    /// chained structs per def).
    ///
    /// @return The def, with a valid cookie.
    /// @par Thread safety
    /// Safe from any thread.
    MRHI_API mrhiInstanceDef mrhiDefaultInstanceDef(void);

    /// Makes an instance.
    ///
    /// @param def          The instance to make.
    /// @param instanceOut  Receives the instance; set to NULL on failure.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument, a def
    /// without its cookie, a zero limit or an allocator with one function;
    /// `mrhi_errorVersion` when the def's contract version is not the
    /// library's; `mrhi_errorUnsupported` for a critical extension the library
    /// does not know; `mrhi_errorCapacity` when the chain is deeper than the
    /// limit or the allocator fails.
    /// @par Thread safety
    /// Safe from any thread.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiCreateInstance(const mrhiInstanceDef* def,
                                                          mrhiInstance** instanceOut);

    /// Destroys an instance. Its devices must be destroyed first.
    ///
    /// @param instance  The instance, or NULL for nothing.
    /// @par Thread safety
    /// Safe from any thread; the instance is used by one thread at a time.
    MRHI_API void mrhiDestroyInstance(mrhiInstance* instance);

#ifdef __cplusplus
}
#endif

#endif // MAUL_RHI_INSTANCE_H
