// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// Pipelines: a shader container's entry points with everything fixed for them,
// made asynchronously and answered in the device's queue. A pipeline's binding
// layout is its container's reflection, and it keeps working after its shader
// is destroyed.
//
// Generated by tools/gen_contract.py from docs/contract/mrhi.json: edit the
// contract, not this file.

#ifndef MAUL_RHI_PIPELINE_H
#define MAUL_RHI_PIPELINE_H

#include "maul-rhi/shader.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

    // A value for a specialization constant, converted to the constant's type:
    // a boolean 0 or 1, an integer within its type's range, or a finite float
    // within 32-bit range.
    typedef struct mrhiConstantValue
    {
        // The constant's id in the container.
        uint32_t id;
        // Its value.
        double value;
    } mrhiConstantValue;

    // A compute pipeline of a device.
    typedef struct mrhiComputePipelineId
    {
        uint32_t index1;
        uint32_t generation;
    } mrhiComputePipelineId;

    // How a compute pipeline is made: a shader's compute entry point and its
    // constants. Build it with mrhiDefaultComputePipelineDef.
    typedef struct mrhiComputePipelineDef
    {
        uint32_t cookie;
        // Extensions, or NULL.
        const mrhiChain* next;
        // A name for debugging tools: UTF-8 without NUL, labelLength bytes, at
        // most MRHI_LABEL_BYTES; NULL when labelLength is 0. Only read during
        // the call.
        const char* label;
        // The label's bytes.
        size_t labelLength;
        // The shader container.
        mrhiShaderId shader;
        // The compute entry point's name, entryLength bytes. Only read during
        // the call.
        const char* entry;
        // The name's bytes.
        size_t entryLength;
        // Values for the container's constants, each id at most once; every
        // constant without a default needs one. NULL when constantCount is 0.
        // Only read during the call.
        const mrhiConstantValue* constants;
        // The values.
        uint32_t constantCount;
    } mrhiComputePipelineDef;

    /// Returns the default compute pipeline def, with no shader or entry, which
    /// must be set.
    ///
    /// @return The def, with a valid cookie.
    /// @par Thread safety
    /// Safe from any thread.
    MRHI_API mrhiComputePipelineDef mrhiDefaultComputePipelineDef(void);

    /// Makes a compute pipeline on a ready device. It returns at once with the
    /// pipeline pending, and the device's queue answers the request with
    /// mrhi_devicePipelineReady; a pipeline is usable once that answer is
    /// mrhi_success.
    ///
    /// @param device       The device.
    /// @param def          The pipeline to make.
    /// @param pipelineOut  Receives the pipeline.
    /// @param requestOut   Receives the id its ready record answers.
    /// @return `mrhi_success` with the pipeline pending; `mrhi_errorInvalid`
    /// for a NULL argument, a def without its cookie, a bad label, an entry the
    /// shader has not as a compute entry, a constant the shader has not, twice,
    /// or with a value its type cannot hold, or a constant without a default
    /// left unset; `mrhi_errorStale` for a shader the device no longer has;
    /// `mrhi_errorUnsupported` for a critical extension the library does not
    /// know; `mrhi_errorState` for a device that is not ready;
    /// `mrhi_errorCapacity` when the device's pipeline limit is reached or its
    /// queue has no room for the answer; `mrhi_errorPlatform` when the driver
    /// refuses at once.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiCreateComputePipeline(mrhiDevice* device,
                                                                 const mrhiComputePipelineDef* def,
                                                                 mrhiComputePipelineId* pipelineOut,
                                                                 mrhiRequestId* requestOut);

    /// Destroys a compute pipeline. A pending one's request is answered with
    /// mrhi_errorStale.
    ///
    /// @param device    The device.
    /// @param pipeline  The pipeline.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL device;
    /// `mrhi_errorStale` for a pipeline the device no longer has.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiDestroyComputePipeline(mrhiDevice* device,
                                                                  mrhiComputePipelineId pipeline);

#ifdef __cplusplus
}
#endif

#endif // MAUL_RHI_PIPELINE_H
