// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// The objects a device owns: samplers, buffers, textures and views, each a
// generation-checked id.
//
// Generated by tools/gen_contract.py from docs/contract/mrhi.json: edit the
// contract, not this file.

#ifndef MAUL_RHI_RESOURCES_H
#define MAUL_RHI_RESOURCES_H

#include "maul-rhi/device.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

    // How texels are filtered.
    typedef uint8_t mrhiFilter;

    enum
    {
        // The nearest texel.
        mrhi_filterNearest = 0,
        // A weighted average of the nearest texels.
        mrhi_filterLinear = 1,
    };

    // How coordinates outside a texture are treated. Clamp to border is absent:
    // WebGPU has no border colors.
    typedef uint8_t mrhiAddressMode;

    enum
    {
        // The edge texel.
        mrhi_addressClampToEdge = 0,
        // The texture repeats.
        mrhi_addressRepeat = 1,
        // The texture repeats, mirrored every other time.
        mrhi_addressMirrorRepeat = 2,
    };

    // A comparison of a new value with a stored one: for comparison samplers,
    // and for depth and stencil tests.
    typedef uint8_t mrhiCompareFunction;

    enum
    {
        // No comparison: a plain sampler.
        mrhi_compareNone = 0,
        // Never passes.
        mrhi_compareNever = 1,
        // Passes when less.
        mrhi_compareLess = 2,
        // Passes when equal.
        mrhi_compareEqual = 3,
        // Passes when less or equal.
        mrhi_compareLessEqual = 4,
        // Passes when greater: reversed-Z depth.
        mrhi_compareGreater = 5,
        // Passes when different.
        mrhi_compareNotEqual = 6,
        // Passes when greater or equal.
        mrhi_compareGreaterEqual = 7,
        // Always passes.
        mrhi_compareAlways = 8,
    };

    // A sampler of a device.
    typedef struct mrhiSamplerId
    {
        uint32_t index1;
        uint32_t generation;
    } mrhiSamplerId;

    // How a sampler is made. Build it with mrhiDefaultSamplerDef.
    typedef struct mrhiSamplerDef
    {
        uint32_t cookie;
        // Extensions, or NULL.
        const mrhiChain* next;
        // Filtering when magnified.
        mrhiFilter magFilter;
        // Filtering when minified.
        mrhiFilter minFilter;
        // Filtering between mip levels.
        mrhiFilter mipFilter;
        mrhiAddressMode addressU;
        mrhiAddressMode addressV;
        mrhiAddressMode addressW;
        // The lowest level of detail sampled, at least 0.
        float lodMin;
        // The highest level of detail sampled, at least lodMin.
        float lodMax;
        // 1 to 16; above 1, every filter must be linear.
        uint16_t maxAnisotropy;
        // A comparison for shadow maps, or mrhi_compareNone.
        mrhiCompareFunction compare;
    } mrhiSamplerDef;

    /// Returns the default sampler def: nearest filtering, clamp to edge,
    /// levels of detail 0 to 32, no anisotropy and no comparison.
    ///
    /// @return The def, with a valid cookie.
    /// @par Thread safety
    /// Safe from any thread.
    MRHI_API mrhiSamplerDef mrhiDefaultSamplerDef(void);

    /// Makes a sampler on a ready device.
    ///
    /// @param device      The device.
    /// @param def         The sampler to make.
    /// @param samplerOut  Receives the sampler.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument, a def
    /// without its cookie, a value out of range, anisotropy with a nearest
    /// filter, or levels of detail out of order; `mrhi_errorState` for a device
    /// that is not ready; `mrhi_errorUnsupported` for a critical extension the
    /// library does not know; `mrhi_errorCapacity` when the device's sampler
    /// limit is reached.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiCreateSampler(mrhiDevice* device,
                                                         const mrhiSamplerDef* def,
                                                         mrhiSamplerId* samplerOut);

    /// Destroys a sampler. Its id ends at once; the device retires it after the
    /// frames that used it.
    ///
    /// @param device   The device.
    /// @param sampler  The sampler.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL device;
    /// `mrhi_errorStale` for a sampler the device no longer has.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiDestroySampler(mrhiDevice* device,
                                                          mrhiSamplerId sampler);

#ifdef __cplusplus
}
#endif

#endif // MAUL_RHI_RESOURCES_H
