// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// Shader containers: SPIR-V and WGSL made offline for each entry point, beside
// one reflection in WebGPU's binding terms, loaded from bytes checked as
// hostile input. docs/contract/container.md gives the layout;
// tools/mrhi_container.py writes it.
//
// Generated by tools/gen_contract.py from docs/contract/mrhi.json: edit the
// contract, not this file.

#ifndef MAUL_RHI_SHADER_H
#define MAUL_RHI_SHADER_H

#include "maul-rhi/frame.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

    // The stages of a pipeline.
    typedef uint32_t mrhiShaderStages;

    enum
    {
        // Vertex shading.
        mrhi_stageVertex = 0x1u,
        // Fragment shading.
        mrhi_stageFragment = 0x2u,
        // Compute.
        mrhi_stageCompute = 0x4u,
    };

    // What a binding slot holds.
    typedef uint8_t mrhiBindingKind;

    enum
    {
        // Nothing: never valid in a container.
        mrhi_bindingNone = 0,
        // A uniform buffer.
        mrhi_bindingUniformBuffer = 1,
        // A storage buffer read and written.
        mrhi_bindingStorageBuffer = 2,
        // A storage buffer only read.
        mrhi_bindingReadOnlyStorageBuffer = 3,
        // A sampler.
        mrhi_bindingSampler = 4,
        // A texture sampled or read.
        mrhi_bindingSampledTexture = 5,
        // A texture read or written as storage.
        mrhi_bindingStorageTexture = 6,
    };

    // The samplers a sampler slot takes.
    typedef uint8_t mrhiSamplerBinding;

    enum
    {
        // Not a sampler slot.
        mrhi_samplerNone = 0,
        // Any sampler.
        mrhi_samplerFiltering = 1,
        // Nearest filtering only, for unfilterable textures.
        mrhi_samplerNonFiltering = 2,
        // A comparison sampler.
        mrhi_samplerComparison = 3,
    };

    // What a sampled texture slot returns.
    typedef uint8_t mrhiSampleType;

    enum
    {
        // Not a sampled texture slot.
        mrhi_sampleNone = 0,
        // Filterable floats.
        mrhi_sampleFloat = 1,
        // Floats, sampled without filtering.
        mrhi_sampleUnfilterableFloat = 2,
        // Depth.
        mrhi_sampleDepth = 3,
        // Signed integers.
        mrhi_sampleSint = 4,
        // Unsigned integers.
        mrhi_sampleUint = 5,
    };

    // How a storage texture slot is used.
    typedef uint8_t mrhiStorageAccess;

    enum
    {
        // Not a storage texture slot.
        mrhi_storageNone = 0,
        // Read.
        mrhi_storageReadOnly = 1,
        // Written.
        mrhi_storageWriteOnly = 2,
        // Read and written.
        mrhi_storageReadWrite = 3,
    };

    // The format of a vertex attribute.
    typedef uint8_t mrhiVertexFormat;

    enum
    {
        // No attribute: never valid.
        mrhi_vertexNone = 0,
        // uint8x2 per vertex.
        mrhi_vertexUint8x2 = 1,
        // uint8x4 per vertex.
        mrhi_vertexUint8x4 = 2,
        // sint8x2 per vertex.
        mrhi_vertexSint8x2 = 3,
        // sint8x4 per vertex.
        mrhi_vertexSint8x4 = 4,
        // unorm8x2 per vertex.
        mrhi_vertexUnorm8x2 = 5,
        // unorm8x4 per vertex.
        mrhi_vertexUnorm8x4 = 6,
        // snorm8x2 per vertex.
        mrhi_vertexSnorm8x2 = 7,
        // snorm8x4 per vertex.
        mrhi_vertexSnorm8x4 = 8,
        // uint16x2 per vertex.
        mrhi_vertexUint16x2 = 9,
        // uint16x4 per vertex.
        mrhi_vertexUint16x4 = 10,
        // sint16x2 per vertex.
        mrhi_vertexSint16x2 = 11,
        // sint16x4 per vertex.
        mrhi_vertexSint16x4 = 12,
        // unorm16x2 per vertex.
        mrhi_vertexUnorm16x2 = 13,
        // unorm16x4 per vertex.
        mrhi_vertexUnorm16x4 = 14,
        // snorm16x2 per vertex.
        mrhi_vertexSnorm16x2 = 15,
        // snorm16x4 per vertex.
        mrhi_vertexSnorm16x4 = 16,
        // float16x2 per vertex.
        mrhi_vertexFloat16x2 = 17,
        // float16x4 per vertex.
        mrhi_vertexFloat16x4 = 18,
        // float32 per vertex.
        mrhi_vertexFloat32 = 19,
        // float32x2 per vertex.
        mrhi_vertexFloat32x2 = 20,
        // float32x3 per vertex.
        mrhi_vertexFloat32x3 = 21,
        // float32x4 per vertex.
        mrhi_vertexFloat32x4 = 22,
        // uint32 per vertex.
        mrhi_vertexUint32 = 23,
        // uint32x2 per vertex.
        mrhi_vertexUint32x2 = 24,
        // uint32x3 per vertex.
        mrhi_vertexUint32x3 = 25,
        // uint32x4 per vertex.
        mrhi_vertexUint32x4 = 26,
        // sint32 per vertex.
        mrhi_vertexSint32 = 27,
        // sint32x2 per vertex.
        mrhi_vertexSint32x2 = 28,
        // sint32x3 per vertex.
        mrhi_vertexSint32x3 = 29,
        // sint32x4 per vertex.
        mrhi_vertexSint32x4 = 30,
        // unorm10_10_10_2 per vertex.
        mrhi_vertexUnorm1010102 = 31,
    };

    // The scalar type of a shader interface variable: a vertex input, a color
    // output or an inter-stage variable.
    typedef uint8_t mrhiScalarType;

    enum
    {
        // Not a variable.
        mrhi_scalarNone = 0,
        // 32-bit floats; a color output of this type suits float, unorm and
        // snorm targets.
        mrhi_scalarFloat32 = 1,
        // 16-bit floats, with the shaderF16 feature; not for vertex inputs.
        mrhi_scalarFloat16 = 2,
        // Signed 32-bit integers.
        mrhi_scalarSint32 = 3,
        // Unsigned 32-bit integers.
        mrhi_scalarUint32 = 4,
    };

    // How an inter-stage variable is interpolated.
    typedef uint8_t mrhiInterpolation;

    enum
    {
        // Not an inter-stage variable.
        mrhi_interpolationNone = 0,
        // Perspective-correct.
        mrhi_interpolationPerspective = 1,
        // Linear in screen space.
        mrhi_interpolationLinear = 2,
        // Not interpolated; required for integers.
        mrhi_interpolationFlat = 3,
    };

    // Where an interpolated inter-stage variable is sampled, or which vertex a
    // flat one takes.
    typedef uint8_t mrhiSampling;

    enum
    {
        // Not an inter-stage variable.
        mrhi_samplingNone = 0,
        // At the pixel's center.
        mrhi_samplingCenter = 1,
        // Inside the covered part of the pixel.
        mrhi_samplingCentroid = 2,
        // Per sample, running the fragment entry per sample.
        mrhi_samplingSample = 3,
        // A flat variable's value from the primitive's first vertex.
        mrhi_samplingFirst = 4,
        // A flat variable's value from either its first or its last vertex.
        mrhi_samplingEither = 5,
    };

    // The fragment builtins an entry point uses that constrain its pipelines.
    typedef uint32_t mrhiShaderBuiltins;

    enum
    {
        // Writes the fragment's depth; its pipelines need a depth format.
        mrhi_builtinFragDepth = 0x1u,
        // Writes the sample mask; its pipelines cannot use alpha to coverage.
        mrhi_builtinSampleMaskOut = 0x2u,
        // Reads whether the primitive faces front; counts as an inter-stage
        // variable.
        mrhi_builtinFrontFacing = 0x4u,
        // Reads the sample index; counts as an inter-stage variable.
        mrhi_builtinSampleIndex = 0x8u,
        // Reads the sample mask; counts as an inter-stage variable.
        mrhi_builtinSampleMaskIn = 0x10u,
        // Reads the primitive index; no device grants it yet, so shaders using
        // it are unsupported.
        mrhi_builtinPrimitiveIndex = 0x20u,
    };

    // The type of a specialization constant.
    typedef uint8_t mrhiConstantType;

    enum
    {
        // Not a constant.
        mrhi_constantNone = 0,
        // A boolean.
        mrhi_constantBool = 1,
        // A signed 32-bit integer.
        mrhi_constantInt32 = 2,
        // An unsigned 32-bit integer.
        mrhi_constantUint32 = 3,
        // A 32-bit float.
        mrhi_constantFloat32 = 4,
    };

// The bytes of a shader container's SHA-256 digest.
#define MRHI_DIGEST_BYTES 32

    // A shader container of a device.
    typedef struct mrhiShaderId
    {
        uint32_t index1;
        uint32_t generation;
    } mrhiShaderId;

    // How a shader container is loaded: its bytes, made by
    // tools/mrhi_container.py. Build it with mrhiDefaultShaderDef.
    typedef struct mrhiShaderDef
    {
        uint32_t cookie;
        // Extensions, or NULL.
        const mrhiChain* next;
        // A name for debugging tools: UTF-8 without NUL, labelLength bytes, at
        // most MRHI_LABEL_BYTES; NULL when labelLength is 0. Only read during
        // the call.
        const char* label;
        // The label's bytes.
        size_t labelLength;
        // The container, 8-byte aligned. Only read during the call.
        const void* bytes;
        // Its size.
        size_t byteCount;
    } mrhiShaderDef;

    // What a loaded shader container holds.
    typedef struct mrhiShaderInfo
    {
        // Its SHA-256 digest.
        uint8_t digest[MRHI_DIGEST_BYTES];
        // Its entry points.
        uint32_t entryCount;
        // Its bindings.
        uint32_t bindingCount;
        // The root block its entry points read.
        uint32_t rootBlockBytes;
    } mrhiShaderInfo;

    /// Returns the default shader def, with no bytes, which must be set.
    ///
    /// @return The def, with a valid cookie.
    /// @par Thread safety
    /// Safe from any thread.
    MRHI_API mrhiShaderDef mrhiDefaultShaderDef(void);

    /// Loads a shader container on a ready device, checking every byte of it as
    /// hostile input.
    ///
    /// @param device     The device.
    /// @param def        The container.
    /// @param shaderOut  Receives the shader.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument, a def
    /// without its cookie, a bad label, or a container that is malformed,
    /// damaged, misaligned or contradicts itself; `mrhi_errorVersion` for a
    /// container of another version; `mrhi_errorUnsupported` for a root block
    /// past the device's limit, 16-bit floats on a device without shaderF16,
    /// the primitive index builtin, or a critical extension the library does
    /// not know; `mrhi_errorState` for a device that is not ready;
    /// `mrhi_errorCapacity` when the device's shader limit is reached or its
    /// allocator fails; `mrhi_errorPlatform` when the driver refuses the code.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiCreateShader(mrhiDevice* device,
                                                        const mrhiShaderDef* def,
                                                        mrhiShaderId* shaderOut);

    /// Destroys a shader container. Pipelines made from it keep working.
    ///
    /// @param device  The device.
    /// @param shader  The shader.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL device;
    /// `mrhi_errorStale` for a shader the device no longer has.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiDestroyShader(mrhiDevice* device, mrhiShaderId shader);

    /// Reads what a shader container holds.
    ///
    /// @param device   The device.
    /// @param shader   The shader.
    /// @param infoOut  Receives what it holds.
    /// @return `mrhi_success`; `mrhi_errorInvalid` for a NULL argument;
    /// `mrhi_errorStale` for a shader the device no longer has.
    /// @par Thread safety
    /// Safe from any thread; the device is used by one thread at a time.
    MRHI_NODISCARD MRHI_API mrhiResult mrhiGetShaderInfo(mrhiDevice* device, mrhiShaderId shader,
                                                         mrhiShaderInfo* infoOut);

#ifdef __cplusplus
}
#endif

#endif // MAUL_RHI_SHADER_H
