// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// The test driver (MAUL_RHI_TEST_DRIVER): a driver without a GPU whose adapters
// a test describes, for the library's tests and a program's own.
//
// Generated by tools/gen_contract.py from docs/contract/mrhi.json: edit the
// contract, not this file.

#ifndef MAUL_RHI_TEST_H
#define MAUL_RHI_TEST_H

#include "maul-rhi/frame.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

    // An adapter the test driver finds: its facts, features and limits, and how
    // a device opening on it ends.
    typedef struct mrhiTestAdapter
    {
        mrhiAdapterInfo info;
        mrhiFeatures features;
        mrhiLimits limits;
        // The outcome of a device opening on the adapter: mrhi_success, or the
        // error the device fails with.
        mrhiResult openOutcome;
        // A format the adapter reports limitedCaps for instead of its usual
        // capabilities, to test adapters below the floor; mrhi_formatNone for
        // none.
        mrhiFormat limitedFormat;
        mrhiFormatCaps limitedCaps;
        // Objects a device on the adapter makes before every further one fails
        // with mrhi_errorPlatform; 0 for no failure.
        uint32_t objectsBeforeFailure;
        // Keeps submitted frames running until a wait with a nonzero timeout,
        // so that a device fills its frames in flight; otherwise frames finish
        // at the next poll.
        bool holdFrames;
        // The outcome its devices' frames finish with; mrhi_success by default.
        mrhiResult frameOutcome;
    } mrhiTestAdapter;

    // Turns the test driver on for an instance, chained on its def with the
    // type mrhi_structTestDriver. The test driver is the only driver of such an
    // instance.
    typedef struct mrhiTestDriverDef
    {
        mrhiChain chain;
        // The adapters the driver finds, in its own order. May be NULL when
        // adapterCount is 0.
        const mrhiTestAdapter* adapters;
        uint32_t adapterCount;
    } mrhiTestDriverDef;

    // A surface of the test driver, chained on a surface def with the type
    // mrhi_structSurfaceSourceTest.
    typedef struct mrhiSurfaceSourceTest
    {
        mrhiChain chain;
        // What the surface can do on the adapters that present to it; the
        // driver adds the floors.
        mrhiSurfaceCaps caps;
        // Bit i set when the test driver def's adapter i presents to it.
        uint32_t presentingAdapters;
        // Makes the surface's creation fail as the platform.
        bool fail;
    } mrhiSurfaceSourceTest;

#ifdef __cplusplus
}
#endif

#endif // MAUL_RHI_TEST_H
