// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// The test driver (MAUL_RHI_TEST_DRIVER): a driver without a GPU whose adapters
// a test describes, for the library's tests and a program's own.
//
// Generated by tools/gen_contract.py from docs/contract/mrhi.json: edit the
// contract, not this file.

#ifndef MAUL_RHI_TEST_H
#define MAUL_RHI_TEST_H

#include "maul-rhi/device.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

    // An adapter the test driver finds: its facts, features and limits, and how
    // a device opening on it ends.
    typedef struct mrhiTestAdapter
    {
        mrhiAdapterInfo info;
        mrhiFeatures features;
        mrhiLimits limits;
        // The outcome of a device opening on the adapter: mrhi_success, or the
        // error the device fails with.
        mrhiResult openOutcome;
    } mrhiTestAdapter;

    // Turns the test driver on for an instance, chained on its def with the
    // type mrhi_structTestDriver. The test driver is the only driver of such an
    // instance.
    typedef struct mrhiTestDriverDef
    {
        mrhiChain chain;
        // The adapters the driver finds, in its own order. May be NULL when
        // adapterCount is 0.
        const mrhiTestAdapter* adapters;
        uint32_t adapterCount;
    } mrhiTestDriverDef;

#ifdef __cplusplus
}
#endif

#endif // MAUL_RHI_TEST_H
