#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sirac Ozmen
#
# Compiles the library's own D3D12 kernels (mrhi-0020) to DXIL with DXC,
# each with its root signature embedded, and writes each as bytes to
# src/generated/NAME.h. DXC signs the DXIL when its validator (libdxil)
# sits beside it. CI runs no DXC; the headers are committed, and this
# script is run again whenever a kernel's source changes.
#
# usage: gen_kernels.py [path to dxc]

import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Each kernel: its source in src/, its header's name, and the array the
# header declares.
KERNELS = [("d3d12_expand.hlsl", "d3d12_expand.h", "mrhiD3d12ExpandDxil")]


def header(source, array, code):
    lines = [
        "// SPDX-License-Identifier: MIT",
        "// Copyright (c) 2026 Sirac Ozmen",
        "//",
        f"// Generated by tools/gen_kernels.py from src/{source}: its DXIL, with",
        "// the root signature embedded.",
        "",
        "// clang-format off",
        "",
        "#include <stdint.h>",
        "",
        f"static const uint8_t {array}[{len(code)}] = {{",
    ]
    for start in range(0, len(code), 12):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in code[start:start + 12]) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    dxc = sys.argv[1] if len(sys.argv) > 1 else "dxc"
    with tempfile.TemporaryDirectory() as work:
        for source, name, array in KERNELS:
            out = os.path.join(work, name + ".dxil")
            subprocess.run([dxc, "-T", "cs_6_0", "-E", "main", "-Qstrip_reflect", "-Qstrip_debug",
                            "-Fo", out, os.path.join(ROOT, "src", source)], check=True)
            with open(out, "rb") as f:
                code = f.read()
            # DXC leaves the hash zero when it cannot sign.
            if code[4:20] == bytes(16):
                sys.exit(f"{source}: DXC did not sign the DXIL; is libdxil beside it?")
            with open(os.path.join(ROOT, "src", "generated", name), "w", encoding="utf-8") as f:
                f.write(header(source, array, code))
            print(f"wrote src/generated/{name} ({len(code)} bytes)")


if __name__ == "__main__":
    main()
