#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sirac Ozmen
#
# Builds the conformance suite's shader container from
# test/shaders/conformance.{vert,frag,comp,wgsl,json} the way a program's
# cook would, offline: glslangValidator compiles each stage under its
# entry name, spirv-link joins them into one module, spirv-val checks it
# for Vulkan 1.3, and tools/mrhi_container.py writes the container,
# which lands in test/shaders/conformance_container.h as bytes. CI runs
# none of these tools; the header is committed, and this script is run
# again whenever a source changes.
#
# usage: gen_test_shaders.py

import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADERS = os.path.join(ROOT, "test", "shaders")
STAGES = (("vert", "vs"), ("frag", "fs"), ("comp", "cs"))
HEADER = os.path.join(SHADERS, "conformance_container.h")


def run(*command):
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"{command[0]} failed:\n{result.stdout}{result.stderr}")


def build(work):
    modules = []
    for suffix, entry in STAGES:
        module = os.path.join(work, entry + ".spv")
        run("glslangValidator", "-V", "--target-env", "vulkan1.3", "-e", entry,
            "--source-entrypoint", "main", "-o", module,
            os.path.join(SHADERS, "conformance." + suffix))
        modules.append(module)
    linked = os.path.join(work, "conformance.spv")
    run("spirv-link", "--target-env", "vulkan1.3", *modules, "-o", linked)
    run("spirv-val", "--target-env", "vulkan1.3", linked)
    container = os.path.join(work, "conformance.mrsc")
    run(sys.executable, os.path.join(ROOT, "tools", "mrhi_container.py"), linked,
        os.path.join(SHADERS, "conformance.wgsl"), os.path.join(SHADERS, "conformance.json"),
        container)
    with open(container, "rb") as file:
        return file.read()


def header(data):
    lines = [
        "// SPDX-License-Identifier: MIT",
        "// Copyright (c) 2026 Sirac Ozmen",
        "//",
        "// The conformance suite's shader container, generated by",
        "// tools/gen_test_shaders.py from test/shaders/conformance.*: edit the",
        "// sources and run the script, not this file.",
        "",
        "#ifndef MAUL_RHI_TEST_CONFORMANCE_CONTAINER_H",
        "#define MAUL_RHI_TEST_CONFORMANCE_CONTAINER_H",
        "",
        "#include <stdalign.h>",
        "#include <stdint.h>",
        "",
        f"alignas(8) static const uint8_t s_conformanceContainer[{len(data)}] = {{",
    ]
    for at in range(0, len(data), 16):
        lines.append("    " + " ".join(f"0x{b:02X}," for b in data[at:at + 16]))
    lines += ["};", "", "#endif // MAUL_RHI_TEST_CONFORMANCE_CONTAINER_H", ""]
    return "\n".join(lines)


def main():
    with tempfile.TemporaryDirectory() as work:
        data = build(work)
    with open(HEADER, "w", encoding="utf-8", newline="\n") as file:
        file.write(header(data))
    print(f"{os.path.relpath(HEADER, ROOT)}: {len(data)} bytes")


if __name__ == "__main__":
    main()
