#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sirac Ozmen
#
# Builds the conformance suite's shader containers the way a program's
# cook would, offline: test/shaders/conformance.{vert,frag,comp,wgsl,json}
# with conformance.{placed.vert,root.frag,add.comp}, and
# test/shaders/bindless.{comp,json}, whose entry reads heaps and so has
# no WGSL. glslangValidator compiles each stage under its entry name,
# spirv-link joins them into one module, spirv-val checks it for Vulkan
# 1.3, and tools/mrhi_container.py writes the container, which lands in
# test/shaders/NAME_container.h as bytes. CI runs none of these tools;
# the headers are committed, and this script is run again whenever a
# source changes.
#
# usage: gen_test_shaders.py

import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADERS = os.path.join(ROOT, "test", "shaders")
# Each container: its name, its stages' sources and entries, and whether
# it has WGSL.
CONTAINERS = (
    ("conformance", (("vert", "vs"), ("frag", "fs"), ("comp", "cs"), ("placed.vert", "vp"),
                     ("root.frag", "fr"), ("add.comp", "ca")), True),
    ("bindless", (("comp", "cs"),), False),
)


def run(*command):
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"{command[0]} failed:\n{result.stdout}{result.stderr}")


def build(work, name, stages, wgsl):
    modules = []
    for suffix, entry in stages:
        module = os.path.join(work, f"{name}_{entry}.spv")
        run("glslangValidator", "-V", "--target-env", "vulkan1.3", "-e", entry,
            "--source-entrypoint", "main", "-o", module,
            os.path.join(SHADERS, f"{name}.{suffix}"))
        modules.append(module)
    linked = os.path.join(work, f"{name}.spv")
    run("spirv-link", "--target-env", "vulkan1.3", *modules, "-o", linked)
    run("spirv-val", "--target-env", "vulkan1.3", linked)
    container = os.path.join(work, f"{name}.mrsc")
    run(sys.executable, os.path.join(ROOT, "tools", "mrhi_container.py"), linked,
        os.path.join(SHADERS, f"{name}.wgsl") if wgsl else "-",
        os.path.join(SHADERS, f"{name}.json"), container)
    with open(container, "rb") as file:
        return file.read()


def header(name, data):
    guard = f"MAUL_RHI_TEST_{name.upper()}_CONTAINER_H"
    lines = [
        "// SPDX-License-Identifier: MIT",
        "// Copyright (c) 2026 Sirac Ozmen",
        "//",
        "// A conformance suite shader container, generated by",
        f"// tools/gen_test_shaders.py from test/shaders/{name}.*: edit the",
        "// sources and run the script, not this file.",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdalign.h>",
        "#include <stdint.h>",
        "",
        f"alignas(8) static const uint8_t s_{name}Container[{len(data)}] = {{",
    ]
    for at in range(0, len(data), 16):
        lines.append("    " + " ".join(f"0x{b:02X}," for b in data[at:at + 16]))
    lines += ["};", "", f"#endif // {guard}", ""]
    return "\n".join(lines)


def main():
    for name, stages, wgsl in CONTAINERS:
        with tempfile.TemporaryDirectory() as work:
            data = build(work, name, stages, wgsl)
        path = os.path.join(SHADERS, f"{name}_container.h")
        with open(path, "w", encoding="utf-8", newline="\n") as file:
            file.write(header(name, data))
        print(f"{os.path.relpath(path, ROOT)}: {len(data)} bytes")


if __name__ == "__main__":
    main()
